### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by scarf** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#1]
All I see is "Error loading extension" in Gnome Tweaks when I tried using source code or ERROR with extensions.gnome.org.  Is there more debug info I can find somewhere?  Using Gnome 3.30.2 on Debian 10 (buster).  Thanks

**Comment by alipirpiran** [comment]
i have tested extension on Gnome 3.34 (On Ubuntu 19).
Could you check and comment error in "Looking Glass". alt + f2, Command "lg". in extensions section find "Crypto Price Tracker", the error could be found there.

**Comment by scarf** [comment]
Thanks for the info.   I just upgrade to Debian testing with Gnome 3.34 and now it's working fine.
