### ISSUE TITLE
After installing new version it still remains old symbols

### ISSUE THREAD

**Issue by Expat72** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#12]
Hi, After I installed the new version on SID it kept the old symbols. Also if I add other symbols all symbols remains as BTC... | ETH....
I also refreshed the session with alt-f2 ->r... still same. any other ideas. where do you persist the coins?

**Comment by azorpax** [comment]
hi @Expat72, yes the `BTC ... | ETH ...` is expected when you enable/disable a coin from your list and the price should display within 10s. 

you mentioned that you've already restarted (alt+f2 r) the gnome session, that should have fixed your problem. 
have you tried just enabling only one coin from your coin list? is it working fine?

**Comment by azorpax** [comment]
This is a similar issue to #13 that was resolved in version 25. 

@alipirpiran, I think this issue can be closed.

**Comment by alipirpiran** [comment]
Ok, I close this issue.
