### ISSUE TITLE
The extension is incompatible with GNOME 43

### ISSUE THREAD

**Issue by Neolot** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#13]
Recently updated to Ubuntu 22.10 (Gnome 43) and the extension stopped working.

```
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _refreshPrice@/home/neolot/.local/share/gnome-shell/extensions/crypto@alipirpiran.github/models/coinItem.js:113:24
  _startTimer/this.timeOutTag<@/home/neolot/.local/share/gnome-shell/extensions/crypto@alipirpiran.github/models/coinItem.js:109:14
```
Hope for your help.
Thanks for your extension, it's very helpful.

**Comment by alipirpiran** [comment]
I don't have gnome 43, but based on your warning text, I added an error handler for promise functions and gnome 43 to the metadata.json file.
Could you check if the problem is fixed?

**Comment by Neolot** [comment]
There are no more errors, but the exchange rate is not displayed, just "ETH ..."

**Comment by Neolot** [comment]
Can I try to fix the issue and send a pull request?

**Comment by alipirpiran** [comment]
Yes, thanks.

**Comment by Neolot** [comment]
I figured out what the problem is. An error occurs during the request (request.js, function get()):
```
TypeError: Soup.SessionAsync is not a constructor
```
It looks like there is some problem with Soup library.
Here is a similar issue: [https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/issues/139](https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/issues/139)

Do you have any ideas how to fix this?

**Comment by papampi** [comment]
+1
I have same issue "BTC..."

**Comment by alipirpiran** [comment]
Hi, 
the Soup library has a major update in the new ubuntu version.
I added support for the new version, but can't check if it works correctly.
could you check the new version, if there is an error send me the error message.

**Comment by papampi** [comment]
Thanks a lot mate
Updated but still shows "BTC..."

**Comment by alipirpiran** [comment]
@papampi 
could you check the error message?
from Looking Glass, run it by pressing Alt-F2, typing lg, then Enter. on extension click on show error.
or in terminal type:
`journalctl -f -o cat /usr/bin/gnome-shell` then restart gnome-shell (alt + f2 + r)

**Comment by Neolot** [comment]
There are no errors in the log now, but catch throws an error:
```
ReferenceError: GLib is not defined
```

**Comment by alipirpiran** [comment]
oh, I forgot to import glib library. thanks

**Comment by alipirpiran** [comment]
I pushed new changes, could you check it

**Comment by Neolot** [comment]
Bingo!
Now it's working, thanks!

**Comment by alipirpiran** [comment]
thanks for your help, I will now send the new version to the extension website.

**Comment by papampi** [comment]
> @papampi could you check the error message? from Looking Glass, run it by pressing Alt-F2, typing lg, then Enter. on extension click on show error. or in terminal type: `journalctl -f -o cat /usr/bin/gnome-shell` then restart gnome-shell (alt + f2 + r)

Sorry just noticed your reply and its already fixed.
Thanks
