### ISSUE TITLE
feature to open chart in the browser

### ISSUE THREAD

**Issue by azorpax** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#14]
Hi @alipirpiran, I want to know if this feature is aligned with your goal for this project.

Currently, when we click an item from the list, it will toggle the switch of the specific item/pair. 
I am thinking of changing that behavior to opening a browser tab to show the live chart of that item/pair. 
And, the toggling will happen when we click only on the switch object.

I can add this feature if you give your green light :)

**Comment by alipirpiran** [comment]
Hi, this would be a good feature. but in my opinion, adding a new button for that is better. a button with an icon like a chart <img src="https://www.iconpacks.net/icons/1/free-chart-icon-646-thumb.png"  width=15></img>
or a link <img src="https://cdn-icons-png.flaticon.com/512/25/25284.png"  width=15></img>
I'm not sure if icon like that exists.

And which website do you want to show the chart on?

**Comment by azorpax** [comment]
yes, a button will do. however, I think changing the current behavior to opening a chart will be beneficial because opening a chart will be more frequently used than toggling the switch (at least from my perspective). 

about the website, it will be based on the current active exchange. 
let's say BTC/USDT pair,  
binance: https://www.binance.com/en/trade/BTC_USDT
okx: https://www.okx.com/markets/spot-info/btc-usdt

**Comment by alipirpiran** [comment]
or just disable toggling when clicking on an item.
for toggling user should click on the switch.
and for the chart, the user should click on the chart button.

because I think a user may accidentally click on a pair, and it opens the browser...
