### ISSUE TITLE
Add Coingecko API

### ISSUE THREAD

**Issue by Strykar** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#19]
Would you consider adding any popular cryptocurrency tracker API, [Coingecko](https://www.coingecko.com/en/api), for example?

This would enable currencies which are not listed on Binance / OKX to be tracked. See https://github.com/alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell/issues/7#issuecomment-1238937772
Examples:
https://www.coingecko.com/en/coins/olympus
https://www.coingecko.com/en/coins/governance-ohm

**Comment by alipirpiran** [comment]
added Coingecko API.

**Comment by Strykar** [comment]
Thank you, time to move away from https://extensions.gnome.org/extension/648/bitcoin-markets/
