### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by Ealrann** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#4]
Thanks for this applet. 

It looks like it's not compatible with gnome 40 : "The extension is incompatible with the current GNOME version" (from the gnome _Extensions_ app).

**Comment by alipirpiran** [comment]
try install it via source code. check if it still has error?

**Comment by Ealrann** [comment]
Same result unfortunately. Here the steps I followed: 
1. delete the folder `~/.local/share/gnome-shell/extensions/crypto@alipirpiran.github/`
2. clone the repo, copy everything back into `~/.local/share/gnome-shell/extensions/crypto@alipirpiran.github/`
3. reboot

**Comment by kahlbald** [comment]
I was going to open a new report but I take advantage of this one to say that it doesn't work in gnome 40 either. Can you fix it, please?

**Comment by alipirpiran** [comment]
currently i am using Ubuntu 20 and gnome 40 is not available for it.
unfortunately i can't test extension on gnome 40 version. but this gnome version has many changes and probably many extensions will have problems on gnome 40.
