### ISSUE TITLE
The extension does not working in Gnome 40.4.0

### ISSUE THREAD

**Issue by Neolot** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#5]
Hi!
I recently updated to Ubuntu 21.10 (Gnome 40.4.0) and the extension does not work in it.
Error:
```
No JS module 'convenience' found in search path
```
Could you fix this error?
Thanks!

**Comment by alipirpiran** [comment]
fixed this
could you install via source code and verify?
or wait till gnome shell website review source.

**Comment by alipirpiran** [comment]
can you access binance.com website ?

**Comment by Neolot** [comment]
Yes, binance.com is working fine
