### ISSUE TITLE
BTC is always displayed even if removed

### ISSUE THREAD

**Issue by tockar** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#8]
Hello, thanks for the extension!
On my setup though (Fedora 34, Gnome 40), while I can add other currencies, BTC is always displayed no matter what. I can disable it, I can remove it, doesn't matter. After relogin/restart/crypto added BTC is added again to the list.

[https://i.imgur.com/ONPSDHJ.png](https://i.imgur.com/ONPSDHJ.png)

**Comment by eldarj** [comment]
+1

**Comment by alipirpiran** [comment]
Fixed the bug
