### ISSUE TITLE
Not working on Gnome 42

### ISSUE THREAD

**Issue by belohnung** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#9]
Im running Gnome 42.0 and the extension does not work, the extension application is showing this:

![image](https://user-images.githubusercontent.com/35181949/162635032-d68acae1-d395-40b4-bee4-0d98b30c3122.png)

**Comment by alipirpiran** [comment]
I currently have Ubuntu 21 (Gnome 40) so i can't debug it. Waiting for Ubuntu 22.04 (Gnome 42) release.

**Comment by alipirpiran** [comment]
Added Gnome 42 support.
